# Event name
name: CI

# When the event should run
on:
  push:
    branches:
      - "**"  # Run on all branches

# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    # What steps within each job
    steps:

      # Set a start time
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> "$GITHUB_ENV"

      # Checkout repository
      - uses: actions/checkout@v4

      # Install Java
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven

      # Run tests
      - name: Run tests with Maven
        run: mvn test

      # Calculate total duration and collect test data
      - name: Collect build data
        if: always()  # Make sure to run even if a previous steps fails
        run: |
        # Calculate total duration
           TOTAL_DURATION=$(( $(date +%s) - START_TIME ))
           echo "TOTAL_DURATION=${TOTAL_DURATION}" >> "$GITHUB_ENV"
           echo "Total duration: ${TOTAL_DURATION} seconds"

        # Extract test results
          bash ./src/test/resources/test_result_script.sh