# Event name
name: on_push

# When the event should run
on:
  push:
    branches:
      - "**"  #This will run on all branches, and must be quoted to be handled by yaml


# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    # What steps within each job
    steps:
      - uses: actions/checkout@v2
      # Install Java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          version: 17
      # Run: mvn test
      - name: Run tests with maven
#        working-directory: ci-observability-lab
        run: mvn test
        # Handle remote server chromedriver

